name: artdiary-be-prod Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew build

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_KEY }}
          source: "build/libs/*-SNAPSHOT.jar"
          target: "/home/ubuntu/artdiary/"
          strip_components: 2

      - name: Set environment variables and restart app
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            cat > /home/ubuntu/artdiary/.env <<EOF
            AWS_RDS_MYSQL_ENDPOINT=${{ secrets.AWS_RDS_MYSQL_ENDPOINT }}
            AWS_RDS_MYSQL_USERNAME=${{ secrets.AWS_RDS_MYSQL_USERNAME }}
            AWS_RDS_MYSQL_PASSWORD=${{ secrets.AWS_RDS_MYSQL_PASSWORD }}
            EOF
            
            export $(cat ~/app/.env | xargs)
            
            pkill -f 'artdiary-*.jar' || true
            nohup java -jar /home/ubuntu/artdiary/artdiary-*.jar --spring.profiles.active=prod > /home/ubuntu/artdiary/app.log 2>&1 &
